# Generated by Django 2.1.5 on 2022-09-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyanomaliesedifiles',
            name='anomalie',
            field=models.ForeignKey(blank=True, db_column='anomalie_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.AnomaliesEdiFileAnnuaire'),
        ),
        migrations.AlterField(
            model_name='historyanomaliesedifiles',
            name='edi_file',
            field=models.ForeignKey(db_column='edi_file_id', on_delete=django.db.models.deletion.CASCADE, to='core.EDIfile'),
        ),
    ]
