# Generated by Django 2.1.5 on 2022-09-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditionnement',
            fields=[
                ('ID_CND', models.IntegerField(primary_key=True, serialize=False)),
                ('CODE_SOC', models.CharField(max_length=45)),
                ('TYPE_COND', models.IntegerField()),
                ('CODE_ARTICLE', models.CharField(max_length=45)),
                ('QTE', models.FloatField(max_length=45)),
            ],
            options={
                'db_table': 'conditionnement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code_client', models.CharField(max_length=45)),
                ('nom_client', models.CharField(max_length=45)),
                ('date', models.DateField(unique=True)),
                ('prep_jour', models.IntegerField()),
                ('UM_jour', models.IntegerField()),
                ('prep_nuit', models.IntegerField()),
                ('UM_nuit', models.IntegerField()),
                ('prep_province', models.IntegerField()),
                ('UM_province', models.IntegerField()),
                ('total_jour', models.FloatField(max_length=45)),
                ('total_nuit', models.FloatField(max_length=45)),
                ('total_province', models.FloatField(max_length=45)),
                ('diff_jour', models.FloatField(max_length=45)),
                ('diff_nuit', models.FloatField(max_length=45)),
                ('diff_province', models.FloatField(max_length=45)),
            ],
            options={
                'db_table': 'facturation_preparation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturationHolidays',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marge', models.IntegerField()),
                ('weekends', models.CharField(max_length=45)),
                ('holidays', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Facturation_holidays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatriceFacturation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code_client', models.CharField(max_length=45)),
                ('nom_client', models.CharField(max_length=45)),
                ('param', models.CharField(max_length=45)),
                ('key', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'matrice_facturation_preparation',
                'managed': False,
            },
        ),
    ]
