# Generated by Django 2.1.5 on 2022-09-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBiRTLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_admin', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'powerbi_rt_log',
                'managed': False,
            },
        ),
    ]
